### ISSUE TITLE
Handle when dataset has no history & when dataset is not FSI linked

### ISSUE THREAD

**Issue by ramfox** [qri-io/desktop#101]
When a dataset is not linked to the FSI, then the concept of 'status' does not mean anything.
When a dataset is linked to the FSI, but no commits have been made, 'history' does not mean anything.

Based on the API change to the `/history` endpoint that returns a 422 error (or a 500 error with `repo: no history`) as the error, when the dataset has no history, and since we already know when a dataset is linked or not, we can make these adjustments!

We pass down hasHistory and linkPath to dataset. If hasHistory === false, and the activeTab is 'history', we should set the active tab to 'status', if linkPath === '', and the activeTab is 'status', we should set the active tab to 'history.

We pass down hasHistory and linkPath to datasetSidebar. If hasHistory === false, don't show the history tab. If linkPath === '', don't show the status tab.

**Comment by dustmop** [comment]
> When a dataset is not linked to the FSI, then the concept of 'status' does not mean anything.

This is not the case. A dataset that isn't checked out uses "status" to compare what changes to state were made at a particular version, for example, "version 2 added a meta and modified the body". The code internally calls this "status at version". I don't think this is best name, but it's close enough to the normal FSI status that it's worth reusing the same terminology. Think of it as "diff but leaner".

> When a dataset is linked to the FSI, but no commits have been made, 'history' does not mean anything.

Sort of. In short, history is agnostic to FSI since it doesn't care at all what's happening in the filesystem, it only cares about what has been committed to the repo. Calls to history should always work the same with or without an "fsi" query parameter. Asking for the history of a dataset with no commits should either return an empty list or a 422, both make sense.

> Based on the API change to the /history endpoint that returns a 422 error (or a 500 error with repo: no history) as the error

The API should never return a 500. By definition doing so indicates that there's a bug in the backend.

I pushed to the `no-history` branch another commit that prevents 500's from happening, but really need to add some tests. Will try and finish that up tomorrow.
