### ISSUE TITLE
bug: strange error message on incorrect login details

### ISSUE THREAD

**Issue by andrew** [qri-io/desktop#476]
When logging in or signing up within desktop with invalid details you get a weird, unhelpful error message: 

> invalid character 'd' looking for beginning of value

Screenshots taken in 0.4.0 on macOS Catalina:

![Screenshot 2020-03-09 at 15 20 45](https://user-images.githubusercontent.com/1060/76229071-90b97880-6219-11ea-9d0d-13b873ea1164.png)
![Screenshot 2020-03-09 at 15 23 53](https://user-images.githubusercontent.com/1060/76229386-04f41c00-621a-11ea-82a8-a9867428f931.png)

**Comment by ramfox** [comment]
Hello! This error is occurring because your Qri repo trying to log into our old registry, rather then qri.cloud. Which means you've been checking out Qri long enough to have been connected to our old registry! Thanks for sticking around :)

To fix this, we need to point your config file to the qri.cloud registry. We need to use the command lline tools to do this right now.

If you have the Qri cli installed (instructions here: https://qri.io/docs/reference/installing-qri-cli), then all you have to do is run this command in your terminal:

`qri config set registry.location https://registry.qri.cloud`

If you've only ever downloaded Qri Desktop, but have never downloaded the binary separately, here is the path on which you can find the binary that is bundled with Qri Desktop:

MacOS: `/Applications/Qri Desktop.app/Contents/Resources/backend/qri`
Windows: `%LOCALAPPDATA%\Programs\Qri Desktop\resources\backend\qri.exe`

So, if you do not have the binary installed and you are on a mac run this command in your terminal:

`/Applications/Qri\ Desktop.app/Contents/Resources/backend/qri config set registry.location https://registry.qri.cloud`

Let me know if that helps!

**Comment by andrew** [comment]
Thanks that sorted it, I did try using the qri cli I already had installed but got another weird error:

```
$ qri config set registry.location https://registry.qri.cloud
-bash: /usr/local/bin/qri: Bad CPU type in executable
```

Using the bundled mac app cli worked fine though.
