### ISSUE TITLE
Importing a CSV whose filename begins with a number causes an error

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#500]
Attempted to drag in a file named `2020-03-24.csv`, import failed because the automatically-generated dataset name would not be valid because it begins with a number.  I confirmed that the same occurs when using the New Dataset modal.

```
{
  "meta": {
    "code": 500,
    "error": "invalid name: dataset name must start with a letter, and only contain letters, numbers, and underscore"
  }
}
```

**Comment by dustmop** [comment]
Ah, right. We should have the name generator take this rule into account.

**Comment by dustmop** [comment]
The plot thickens! Using a filename like "2018_winners.csv" works because the inference creates the name `me/winnerscsv`, but that fails if the *entire* filename is non-alphanumeric. We should use a name like `me/untitled` for cases like this, or prepend a string to end up with some like `me/dataset_2020_03_24csv`.

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/qri/pull/1223.
