### ISSUE TITLE
Clicking "Meta" on History after fresh Checkout crashes

### ISSUE THREAD

**Issue by rustprooflabs** [qri-io/desktop#545]
# Details

Qri v0.9.8, Qri Desktop 0.4.2.

Windows 10 Pro.

I created a new dataset, everything looks good.  After checking out the initial time, I am presented with the the dataset's History tab.  The "Meta" and other options in the main area of the app are **not** grayed out at this time. 

![image](https://user-images.githubusercontent.com/3085224/80759285-4c00de00-8af4-11ea-9feb-8c11db4bfbf0.png)

 I click on the "Meta" tab, and get the Dang. It broke. message.  The Send Crash report does not give me any indication that it is sending anything either, I did try clicking that before submitting this bug!  If you received a few dozen identical crash reports from me... sorry!

![image](https://user-images.githubusercontent.com/3085224/80759362-6d61ca00-8af4-11ea-99e1-6143653b6b4f.png)

If I click the "Status" tab right after checkout (instead of clicking "Meta" first), when I switch back to the History tab, the Meta option is grayed out, preventing my click and crash.  

I checked the debug logs but did not see anything related to this error.  Let me know if it would helpful to include and I can reproduce the error.

**Comment by uhLeeshUh** [comment]
Adding to this - this is likely similar to a user reported issue in Sprint R:

“I seemed to figure it out, then I checked out the meta tab, and it crashed.”

**Comment by dustmop** [comment]
I was able to repro this, on macos, so we know it's not Windows specific. Looking into it.

**Comment by dustmop** [comment]
```
Metadata.tsx:120 Uncaught TypeError: Cannot read property 'accessURL' of undefined
    at Metadata.tsx:120
    at Array.filter (<anonymous>)
    at MetadataComponent (Metadata.tsx:120)
    at MetadataComponent (react-hot-loader.development.js:827)
    at renderWithHooks (react-dom.development.js:16241)
    at updateFunctionComponent (react-dom.development.js:18328)
    at beginWork$1 (react-dom.development.js:20151)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
(anonymous) @ Metadata.tsx:120
MetadataComponent @ Metadata.tsx:120
MetadataComponent @ react-hot-loader.development.js:827
renderWithHooks @ react-dom.development.js:16241
```

The line of code is: https://github.com/qri-io/desktop/blob/master/app/components/collection/datasetComponents/Metadata.tsx#L120

After a checkout, none of the components are disabled, so clicking on Meta is possible. The code to handle that component crashes because `standardField` is undefined, though I'm unclear why that is.

One part of the fix is correctly disabling buttons that should not be clickable, but I'm wondering if there's something that also needs to be fixed inside the Metadata component in order to make it not crash.

**Comment by dustmop** [comment]
Slight misdiagnosis, the `data` parameter to `MetadataComponent`'s render function is empty, which is why that line fails. A work-around that would quickly prevent a crash would be just returning an empty component in this case.

**Comment by ramfox** [comment]
I'm sure there are other aspects to clean up, but the bug here is that when we checkout a dataset, we end up triggering a succession of fetches: `linkDatasetAndFetch`. One of those fetches is to `fetchWorkingDatasetDetails`, which populates everything you need to edit a dataset. It lives in the `workingDataset` reducer.

We also have a `DatasetReducer`, that contains all the information we need to display an already committed version of a dataset. We needed these two separate reducers so we don't have to re-fetch when we clicked back and forth between "status" and "history".

However, as you can imagine, if we are fetching the `workingDatasetDetails` of a dataset that is different from the one that we have stored in the `DatasetReducer` (or vice-versa), we should clear the `DatasetReducer` so we don't have information on two different datasets stored in our state tree. We do a check in the `DatasetReducer` to make sure if an `API_DATASET_REQUEST` comes through the reducer & it's requesting information on a dataset different from the one we have stored, we reset the reducer. We do that by comparing the information in the `action` that is passing through with the information we have stored in the `state`.

In a recent-ish refractor, we renamed most of the references to `peername` in the code (except for in the `Dataset` structure, since it is still `Peername` in the qri backend) to `username`. However, in the `DatasetReducer` (`/app/reducers/dataset.ts`), we've missed one.

line 51, `action.segments.peername` should be `action.segments.username`.

That will fix the bug, but again, I'm sure there are many things that can be improved.

eg, we should add a new test file `/test/reducers/dataset.test.ts` that tests that this has been fixed.

**Comment by dustmop** [comment]
This was fixed by the recent refactoring / redesign of Desktop, and appears to no longer be an issue.
