### ISSUE TITLE
Collection View Refactor

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#554]
Improvements for the Collection view will allow the user to quickly understand the status of datasets in their Qri collection, find datasets to work with, and perform dataset-level actions (publish/unpublish, remove, etc).  The collection view is "home base" and is where users will take control of their datasets: pushing, pulling, removing, finding, and just understanding what they have.

This work assumes refactoring of the top-level layout of Qri Desktop, with a fixed-height header running the full width of the content pane.  (The current layout uses split sidebar/content on all views without a unified header)

Major Functionality
- List of Datasets - The list shows all datasets in the Qri collection, and is sortable by clicking the 

- Filtering -  The user can filter by string match or date range of last update (we can add more filters later, these are two simple ones to start with) Filter pane can get more complex as users demand more ways to navigate large collections.  One idea is to have a collapsible advanced filter section.

- Dataset status glyphs - Status glyphs provide a quick visual indicator of published/unpublished, file system integration, and sync.   

- Dataset actions - An ellipses icon at the end of each row shows a context menu with dataset-level actions (remove, duplicated, publish, etc)

- Multiselect - User can select multiple datasets using checkboxes and perform bulk actions.

TODO:
- Indicate how many datasets are currently selected, visually highlight selected datasets in addition to the checkbox 
- Warning UI for remove/publish - These currently exist in the app, but would need to be modified to handle multi-select actions
- Think about keyboard-only navigation and actions
- Syncing UI - clearly show that Qri is pulling new data
- Visual indication that a dataset has "new" data that the user hasn't seen yet

![Qri_Desktop_0_4_0_-_v4_sketch](https://user-images.githubusercontent.com/1833820/86026203-1fd2e200-b9fd-11ea-8396-65728525534b.png)

**Comment by uhLeeshUh** [comment]
@chriswhong thanks for putting this together! I have a couple of questions for you about the design and then also would appreciate any feedback you have on how I'm thinking of breaking this down into parts (I also only focused on the Major Functionality bullets for now if that's ok). Once I get your OK, I can split this issue into a handful of smaller ones 

**Questions I have:**

- When you mention this work assumes the refactoring of the top-level layout of Qri Desktop with a new fixed-height header, are you imagining that's a ticket I should first tackle as a blocker to this?
- To piggyback off the first question, does the new header include the search bar in all views except this one (since I imagine filtering on "All datasets" is effectively the same)?
- Just to confirm -- the count of matching datasets is the total count (inclusive of what is not yet rendered by infinite scroll), right? Not the count of the subset that is currently rendered?
- Which columns are sortable? Is it everything except status? 

**Ideas for smaller tickets (my hand-wavy heuristic here is breaking down into what feels like ~1 day's worth of work):**

- Create a new shared header component to be used in each Desktop view. For Collections view, top-level actions like "Pull Dataset" and "New Dataset"
- Get datasets to render (both My Datasets and All Datasets) in new table (with a hardcoded count at first and no functionality yet for last 2 columns) where clicking on a row navigates to dataset view
- Add infinite scroll to datasets
- Add in status glyphs functionality
- Add in dataset actions
- Add sort functionality (may want to break this up by column into mini tickets)
- Add filter panel & matching data set count
- Add in multiselect functionality

**Comment by chriswhong** [comment]
> When you mention this work assumes the refactoring of the top-level layout of Qri Desktop with a new fixed-height header, are you imagining that's a ticket I should first tackle as a blocker to this?

Yes, I think it's best to make sure the header works consistently across the app, but it also might be possible to just build it for this view and integrate it into other views later.

> To piggyback off the first question, does the new header include the search bar in all views except this one (since I imagine filtering on "All datasets" is effectively the same)?

There's been plenty of debate over search in desktop, and switching between "search for datasets in cloud" and "search locally".   I think the current implementation needs work, but I lean more towards search not being an app-wide thing, but having each view have its own version of search/filter that makes sense for what it is doing.  So I'd say keep it out for now, but we should talk and vision about it soon.

> Just to confirm -- the count of matching datasets is the total count (inclusive of what is not yet rendered by infinite scroll), right? Not the count of the subset that is currently rendered?

Yes, the count should confirm the total count that matches the current filters.

> Which columns are sortable? Is it everything except status?

This sounds right to me.

**Comment by uhLeeshUh** [comment]
I've cut issue #576 to build the "skeleton" views of each new component required for this full Collection view. Once those are reviewed, I'll cut a new issue for the remainder of the work (wiring-up the new components to our API)

**Comment by uhLeeshUh** [comment]
@chriswhong a couple more quick questions here:
1. The left pane with the icons is no longer re-sizable, correct? I assume since we're no longer showing data there about datasets that there isn't user value to resizing it but just want to double check
2. Is there anywhere that we want to persist the current "You have {x} local datasets" info that I see in the current Collection view? Or is that now covered by our "Linked to filesystem" status glyph?

**Comment by chriswhong** [comment]
1. Correct, the navigation bar on the left is not resizable
2. I think if there are no filters applied, that should go where it says "Showing 27 matching datasets". If there are no filters, maybe it could say "Showing all 32 local datasets"

**Comment by uhLeeshUh** [comment]
Note: this work has been de-prioritized in favor of focusing on Qri Cloud. Currently `Header` and `DatasetStatus` components have been built out via #576 but the rest of the work is on pause
