### ISSUE TITLE
feat(components): `IncompatibleBackend`, `MigratingBackend`, `MigrationFailed` components

### ISSUE THREAD

**Issue by ramfox** [qri-io/desktop#567]
We need three new components!

They should each the `WelcomeTemplate` component.

* [x] `IncompatibleBackend` - props `{ incompatibleVersion: string }`. Should import the expected backend version number (from `version.js`), and says something to the effect of "Incorrect backend version supplied. Expected qri v${expectedVersion}, but have ${incompatibleVersion}. Please file a issue here."
* [x] `MigratingBackend` - "Migrating the Qri backend! This might take a minute..." W/ a loading spinner
* [x] `MigrationFailed` - "The Qri backend migration failed! Try reloading the app, or send a crash report to the Qri team by etc"

**Comment by uhLeeshUh** [comment]
Note: this issue is being expanded to cover the refactoring of the `ErrorHandler` component which currently contains logic to: 

1. Send a crash report
2. Reload the app

Since `ErrorHandler` is situated as a last-resort error catcher in the app, we'll modularize its logic to be used separately in the new internal `MigrationFailed` component which will give users that optionality when a backend migration fails
