### ISSUE TITLE
refactor(NavTopbar): remove forward arrow & back arrow should take you to the base url of that view

### ISSUE THREAD

**Issue by ramfox** [qri-io/desktop#607]
Eg, if we are on the collections page & then click into a dataset, the "back" arrow should return us to the collections page.

If we are in the network tab & we click into a dataset, the "back" arrow should return us to the network page.

**Comment by uhLeeshUh** [comment]
@ramfox I just tried repro-ing this per your comment above and the back arrow seems to work as expected ("if we are on the collections page & then click into a dataset, the "back" arrow should return us to the collections page" and "If we are in the network tab & we click into a dataset, the "back" arrow should return us to the network page." both work). 

Was this already fixed, or is the ticket saying "if I'm on collections, click into a dataset, click around a few commits, and then click back, I would expect to go back to the collections page instead of whatever last commit I was on?" This case seems a little confusing to me but want to make sure I understand the issue

**Comment by ramfox** [comment]
might have changed in the master branch, but in the branch I'm working on right now, the back button just walks backwards through history.

We want to remove the forward button and have the back button just take us back to the main view at that route. EG, if you are at `/collection/edit/username/dataset/body` the back button takes you to `/collection`. If you are `/network/friends_username/dataset/meta/at/ipfs/Qmfoo` the back button takes you to `/network`

**Comment by uhLeeshUh** [comment]
Got it. Something I was thinking there as a possible edge case then is if I'm at something like `/collection/edit/username/dataset/body`, then navigate to `/network` and click back, I still want to go back to `/collection/edit/username/dataset/body`, right? Even though the base of my current route is `/network`? So to rephrase, we only want to go to the main view at that route if the previous entry on the history stack was also at the same base, right? 

e.g. `/collection` --> `/collection/edit/username/dataset/body` --> click back = `/collection`
but `/collection` --> `/collection/edit/username/dataset/body` --> click icon to `/network` --> click back = `/collection/edit/username/dataset/body` ?

**Comment by ramfox** [comment]
ummm to my understanding, and we should loop @chriswhong into this convo, but I think the idea might be that if you are on the `/network` or `/collection` view the back button would be disabled

If you take a look at the `keybase` app we are following that pattern. It's not an exact 1-to-1 match of behavior, but for the back button, that's the model.

**Comment by uhLeeshUh** [comment]
awesome, just checked out how keybase does it and that makes sense to me! ty
