### ISSUE TITLE
User can update Profile

### ISSUE THREAD

**Issue by chriswhong** [qri-io/desktop#64]
User can update their profile.  Use the same implementation as in qri desktop.  

![image](https://user-images.githubusercontent.com/1833820/61981739-7acbb000-afc8-11e9-8ddc-bb38dba65f30.png)

**Comment by b5** [comment]
I think we should do this on qri cloud, especially if we're going to do hosted profile photos

**Comment by dustmop** [comment]
An extra wrinkle on this: it's possible currently to rename your peer on the command-line, either by using `qri config set peername ...`, or by editing your config.yaml. However, ds_refs stores dataset information, and some commands will fail if they see a profile name that doesn't match the profileID. Basically, we should be treating profileIDs as authoritative, and the peername as just presentation, but not all of our codebase does this. Some of this logic is handled by CanonicalizePeername and CanonicalizeDatasetRef, but since these are considered accessors, neither of these will write updated peernames back to ds_refs. Not sure how to architect it, but something in our stack should be detecting peername changes and writing them back to ds_refs.

**Comment by chriswhong** [comment]
Closing, profile updates happen in Qri Cloud
